# Generated by Django 5.2.9 on 2025-12-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Production", "Production"),
                    ("Quality Control", "Quality Control"),
                    ("R&D", "R&D"),
                    ("Warehouse", "Warehouse"),
                    ("Facilities", "Facilities"),
                    ("IT & Admin", "IT & Admin"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
